# Model-Cache Pre-Warm (CI setup)
#################################

"""Download the local model assets bucket A needs, then prove they work offline.

WHY THIS EXISTS
---------------
`tests/test_agent_retrieval_observability.py` SECTION A measures the REAL
FastEmbed ``Qdrant/bm25`` model:

    check("stopwords-only yields no BM25 terms",
          sparse_token_count("the of and a an is to"), 0)

That asserts the model has a stopword list and applies it -- a fact about the
downloaded asset (``english.txt`` in the snapshot), not about any code in this
repository. A stand-in cannot establish it: a stub returning 0 would make the
check agree with itself by construction, which is the defect this project's own
rules exist to remove. So the asset has to be REAL, and the only question is
WHEN it arrives.

Before this script it arrived AT TEST TIME. MEASURED with a recorder that
logged and REFUSED every outbound attempt it intercepted: on a cold cache
``deps.get_bm25_query_model()`` reaches ``huggingface.co`` and raises when
blocked. A hosted runner starts cold, so every CI run was downloading a model
inside the test step while that file's bucket-A entry said it "makes no live
call". THAT INSTRUMENT REPORTS WHAT IT INTERCEPTED IN THE PROCESSES IT WAS
LOADED INTO; total egress from a run was not independently measured.

WHAT THIS BUYS, STATED HONESTLY
-------------------------------
IT DOES NOT MAKE THE PROJECT NETWORK-FREE. It moves ONE download from test time
to SETUP time and then proves the tests do not need the network afterwards.
The honest claim, and the one written into
``.github/scripts/ci_test_buckets.py``'s entry for that file, is:

    the asset is fetched at CI SETUP, and the test step runs offline.

WHAT IS PINNED, AND WHAT CANNOT BE
----------------------------------
  * the MODEL NAME is ``oncotriage.embedding.BM25_SPARSE_MODEL_NAME`` -- one
    owner, already asserted to have exactly one construction site by
    tests/test_package_invariants.py section 2f;
  * the LIBRARY is ``fastembed==0.7.4`` in pyproject.toml;
  * the REVISION cannot be pinned here. ``SparseTextEmbedding`` takes no
    ``revision=`` argument, so fastembed resolves the snapshot itself. It is
    REPORTED instead -- printed with the file inventory and each blob's sha256 --
    so a change upstream is visible in the CI log rather than silent. Adding a
    revision knob nothing reads would be the dead-tunable shape this project
    deletes.

THE VERIFICATION RUNS IN A SUBPROCESS, AND THAT IS NOT A DETAIL
---------------------------------------------------------------
``oncotriage.embedding`` caches the model in a module global for the life of the
process, so an in-process check after the warm would pass whether or not a
single byte reached the cache directory. The check therefore runs in a FRESH
interpreter with ``HF_HUB_OFFLINE=1``, which is the same enforcement the CI test
steps use: if the cache is incomplete, this fails at SETUP with a named
diagnosis instead of at test time with a download or a timeout.

WHAT IT DELIBERATELY DOES NOT ASSERT
------------------------------------
The stopword and tokenization FACTS above are
``tests/test_agent_retrieval_observability.py``'s alone and are not restated
here. Two copies of one expectation is the shape this project keeps removing,
and the copy in the test is the one with the argument attached. What this
asserts is COMPLETENESS: the model loads offline and produces a non-empty term
list for a known descriptor -- the minimum non-degeneracy, without which "it
loaded" would be satisfied by a model that returns nothing for everything.

WHAT IT DOES NOT WARM, MEASURED RATHER THAN ASSUMED
---------------------------------------------------
MedCPT. Every bucket-A file that names a MedCPT accessor either sets
``ONCOTRIAGE_DEFER_LOCAL_MODELS`` above its imports or installs an override
through ``oncotriage.agent.deps``. Verified by running the two that do neither
-- ``test_agent_ablation_flag_passthrough.py`` and
``test_storage_inference_logging_contract.py`` -- against a COLD cache with
every outbound attempt refused: both exit 0 with ZERO external attempts.

RESIDUAL, STATED RATHER THAN LEFT TO BE DISCOVERED
--------------------------------------------------
A blob that is PRESENT but silently WRONG -- a corrupted download that still
parses as a word list -- is not caught here. Detecting that needs a per-file
sha256 manifest checked against a pinned revision, and the revision cannot be
pinned (above), so such a manifest would have to be regenerated by hand every
time upstream moves and would be a second declaration that can disagree with
the model. What WOULD catch it is
``tests/test_agent_retrieval_observability.py``'s own behavioural checks, in
the same CI job minutes later -- reported there as a test failure rather than
as a cache failure, which is a worse diagnosis than this step gives but is not
a silent pass.

Exit codes:
    0 -- the cache is warm, every snapshot entry resolves, and a fresh
         interpreter loaded it with the hub's offline switch set
    1 -- the warm, the integrity check or the offline verification failed
"""

import os
import subprocess
import sys


_CODE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# THE OFFLINE SWITCH HAS ONE SPELLING IN THIS REPOSITORY. It is huggingface_hub's
# own documented opt-out, it is what the verification below runs under, and it
# is what the CI test steps export. Named here so the two cannot drift.
HF_OFFLINE_ENV = "HF_HUB_OFFLINE"

# The probe is a non-degeneracy check, not a behavioural pin: see the module
# docstring. "Lung Neoplasms" is a MeSH descriptor the pipeline really queries
# with, so a model that tokenizes it to nothing is broken in a way that matters.
_PROBE_TEXT = "Lung Neoplasms"

_VERIFY = f'''
import sys
from oncotriage.agent import deps
model = deps.get_bm25_query_model()
n = len(next(model.query_embed({_PROBE_TEXT!r})).indices)
print("VERIFY_INDICES=%d" % n)
sys.exit(0 if n > 0 else 1)
'''


def deps_defer_env():
    """The name of the skip-local-models switch, from its one owner.

    Read through `oncotriage.agent.deps` rather than written out, so this
    refusal cannot name a variable the package has renamed.
    """
    from oncotriage.agent import deps
    return deps.DEFER_LOCAL_MODELS_ENV


def _inventory(cache_dir, model_name):
    """(revision, [(filename, size, sha256)], [broken]) for the snapshot.

    `broken` is every entry the snapshot lists that does not resolve to a
    readable file. IT IS THE POINT OF THIS FUNCTION, not a by-product.

    huggingface_hub stores a snapshot as a directory of SYMLINKS into a shared
    `blobs/` directory. A blob that is missing leaves a dangling link -- and
    MEASURED, on this model, that failure is completely silent: with
    `english.txt`'s blob removed the model still constructs, still embeds, makes
    no outbound attempt the recorder saw, and raises nothing, while
    `query_embed("the of and a an is to")` goes from 0 terms to 7 because the
    stopword list it could not read is simply not applied. Nothing downstream
    would say the cache was the cause.

    The first version of this function tested `os.path.isfile` and `continue`d,
    which SKIPS a dangling link -- so a damaged cache produced a shorter
    inventory that read exactly like a smaller model. A control caught it.

    Returns (None, [], []) when the layout is not the huggingface_hub shape this
    reads, because an inventory this script could not take must not read as an
    empty model; `main` reports that case rather than passing on it.
    """
    import hashlib

    if not cache_dir:
        return None, [], []
    repo = "models--" + model_name.replace("/", "--")
    root = os.path.join(cache_dir, repo)
    ref = os.path.join(root, "refs", "main")
    if not os.path.isfile(ref):
        return None, [], []
    with open(ref) as fh:
        revision = fh.read().strip()
    snap = os.path.join(root, "snapshots", revision)
    if not os.path.isdir(snap):
        return revision, [], []
    rows, broken = [], []
    for name in sorted(os.listdir(snap)):
        target = os.path.join(snap, name)
        try:
            with open(target, "rb") as fh:
                blob = fh.read()
        except OSError as exc:
            broken.append(f"{name}: {type(exc).__name__}: {exc}")
            continue
        rows.append((name, len(blob), hashlib.sha256(blob).hexdigest()[:16]))
    return revision, rows, broken


def main():
    print("=" * 74)
    print("MODEL CACHE PRE-WARM")
    print("=" * 74)

    # THE ONE CONSTRUCTION SITE. This calls oncotriage.embedding rather than
    # constructing SparseTextEmbedding, so this script adds no second site and
    # warms exactly the object the pipeline and the test will use.
    from oncotriage import embedding, paths

    name = embedding.BM25_SPARSE_MODEL_NAME
    print(f"  model:      {name}")

    # `pin_model_cache` returns WHERE THE CACHE IS, in both cases.
    # `fastembed_cache_dir()` answers a different question -- what to pass as
    # `cache_dir=` -- and it returns None when the operator's own
    # FASTEMBED_CACHE_PATH decided, because the library reads that variable
    # itself. Reading the inventory from THAT would crash on exactly the
    # configuration a CI runner or a developer with an exported cache path
    # uses; it did, in this script's first version, and a control caught it.
    var, value, source = paths.pin_model_cache(paths.MODEL_CACHE_ENV_FASTEMBED)
    cache_dir = value
    print(f"  cache root: {var}={value} (source: {source})")
    print(f"  cache_dir= passed to the constructor: "
          f"{paths.fastembed_cache_dir()!r} "
          f"(None means the variable above decided, which is correct)")

    if os.environ.get(HF_OFFLINE_ENV):
        print(f"  FATAL: {HF_OFFLINE_ENV} is set, so this step cannot fetch "
              f"anything. It is the TEST steps that run offline; this one is "
              f"the download.")
        return 1

    # THE OTHER VARIABLE THAT MAKES THIS STEP IMPOSSIBLE, refused for the same
    # reason and by name. With it set, `deps.get_bm25_query_model()` -- the
    # accessor the verification uses, because it is the one the test uses --
    # hands back a `_DeferredLocalModel` placeholder that raises on attribute
    # access. The verification would then fail with a message about a
    # placeholder, which is true and is a worse diagnosis than this one.
    if os.environ.get(deps_defer_env()) == "1":
        print(f"  FATAL: {deps_defer_env()}=1 is set. That switch exists so a "
              f"replay harness can skip loading local models; this step's whole "
              f"job is to load one. Unset it for this step.")
        return 1

    print(f"\n  Fetching (this is the ONE network access; the test step is "
          f"offline)...")
    try:
        embedding.get_bm25_sparse_model()
    except Exception as exc:                                # pragma: no cover
        print(f"  FATAL: could not warm {name}: "
              f"{type(exc).__name__}: {exc}")
        return 1

    revision, rows, broken = _inventory(cache_dir, name)
    print(f"\n  resolved revision: {revision or '<not in the expected layout>'}")
    if rows:
        print(f"  {len(rows)} file(s):")
        for fname, size, digest in rows:
            print(f"      {digest}  {size:>8}  {fname}")
    if not rows and not broken:
        print("  inventory unavailable (layout not recognised); the offline "
              "verification below is the only thing deciding this step. See "
              "the RESIDUAL note at the end of this file.")

    # THE INTEGRITY CHECK, AND IT IS THE ONE THAT CATCHES THE SILENT CASE.
    # A dangling link does not stop the model loading -- it stops one stopword
    # list being applied, with no exception and no network attempt. Only this
    # says so.
    if broken:
        print(f"\n  FATAL: {len(broken)} snapshot entr(ies) do not resolve to a "
              f"readable file. The model would still LOAD and would silently "
              f"behave differently:")
        for entry in broken:
            print(f"      {entry}")
        print(f"  Remove {cache_dir!r} and re-run this step to re-fetch.")
        return 1

    # THE VERIFICATION, IN A FRESH INTERPRETER. See the module docstring: this
    # process already holds the model in a module global, so only a new one can
    # say whether the CACHE is complete.
    print(f"\n  Verifying offline usability ({HF_OFFLINE_ENV}=1, fresh "
          f"interpreter)...")
    env = dict(os.environ)
    env[HF_OFFLINE_ENV] = "1"
    completed = subprocess.run([sys.executable, "-c", _VERIFY],
                               cwd=_CODE_DIR, env=env,
                               capture_output=True, text=True)
    indices = None
    for line in completed.stdout.splitlines():
        if line.startswith("VERIFY_INDICES="):
            indices = int(line.split("=", 1)[1])

    if completed.returncode != 0 or not indices:
        print(f"  FATAL: the cache is not usable offline "
              f"(exit {completed.returncode}, indices={indices}).")
        print("  --- stdout ---")
        sys.stdout.write(completed.stdout[-2000:])
        print("  --- stderr ---")
        sys.stdout.write(completed.stderr[-2000:])
        return 1

    print(f"  OK: loaded under {HF_OFFLINE_ENV}=1 and tokenized "
          f"{_PROBE_TEXT!r} to {indices} term(s).")
    print(f"\n  The test step may now run with {HF_OFFLINE_ENV}=1.")
    return 0


if __name__ == "__main__":
    sys.exit(main())


#------------------------------------------------------------------------------


#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  9 2026

@author: ramyalsaffar
"""
