# Create DAG
############

"""
Generate the ``trial_refresh_weekly`` DAG and write it under {airflow_path}/dags/.

After running this file, in a terminal, run these:
    ## Terminal 1: Start API server
    ## export AIRFLOW_HOME="/path/to/airflow/"
    ## airflow api-server --port 8080

    # Terminal 2: Start scheduler
    ## export AIRFLOW_HOME="/path/to/airflow/"
    ## airflow scheduler

    # Check DAG status via UI: http://localhost:8080
    # Or trigger manually: airflow dags trigger trial_refresh_weekly

After running this file (which writes the DAG to the dags/ folder),
use file 24, Airflow Manager, to start Airflow services, check status, and trigger.

THIN ENTRY POINT (item 20c, pass 3c-2)
--------------------------------------
The three string pieces and the writer moved to
``oncotriage/orchestration/dag_generator.py``. What is left here is a
``__main__`` guard and one call.

THE GENERATED BYTES DID NOT CHANGE, and that was proved rather than assumed:
pass 3c-2 generated the DAG from git HEAD's version of this file into one
temporary directory, generated it from the package module into another, and
compared. Byte-identical, sha256 68963b0cc3e4cac54a96c550b251e24c5fbb312bb1aace44b62943698bf82731.
That is the only acceptance criterion that matters here, because the scheduler
parses the OUTPUT and never sees this file.

WHAT DID CHANGE: ``dag_content`` is built by a call rather than assembled at
module level. It had to be. Its middle third is %-formatted with ``code_path``,
``keys_path`` and ``data_trial_path``, all three of which are lazy paths in
``oncotriage.paths``, so assembling it at module level resolved three
directories at import.

NO EXEC BOOTSTRAP and NO RE-EXPORT SHIM. Nothing in the repository reads this
file's namespace -- all five top-level names (``dag_content_head``,
``_dag_path_block``, ``dag_content_tail``, ``dag_content``, ``write_dag_file``)
were grepped against every .py, .md, .toml and .yml in the tree and not one has
a hit outside this file.

Run from terminal:
    python "23- Airflow DAG.py"

It will NOT overwrite an existing DAG whose text differs from the generator. To
regenerate after a change:
    rm "{airflow_path}/dags/trial_refresh_weekly.py" && python "23- Airflow DAG.py"
"""

import os
import sys


# Make the oncotriage package importable
#---------------------------------------
# See the same block in "04- FHIR Generate Data.py" and "16- Database Query.py".
try:
    import oncotriage  # noqa: F401
except ImportError:
    for _candidate, _how in (
        (os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals()
         else None, "__file__"),
        (os.getcwd(), "cwd"),
    ):
        if _candidate and os.path.isdir(os.path.join(_candidate, "oncotriage")):
            if _candidate not in sys.path:
                sys.path.insert(0, _candidate)
            print(f"[Bootstrap] oncotriage package found at {_candidate} "
                  f"(via {_how}); added to sys.path")
            break
    else:
        raise
    del _candidate, _how

from oncotriage.orchestration.dag_generator import write_dag_file_to_default


#------------------------------------------------------------------------------


# Write DAG file
# Item 20b: creating the dags/ directory and writing the file were both module
# level, so loading this file wrote to disk.
if __name__ == "__main__":
    write_dag_file_to_default()


#------------------------------------------------------------------------------


#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 16 17:08:13 2026

@author: ramyalsaffar
"""
