# ECOG Performance Status Surfacing Test
#########################################

"""
ECOG Performance Status Surfacing Test

Covers routing LOINC 89247-1 out of the general observation pool and into a
first-class field that reaches GPT-4o.

The defect: File 07 sent every observation that was not an mCODE stage group or
genomic variant into patient_data['observations']. ECOG landed there and then
died there. OncologyLabRegistry does not carry 89247-1, so the summary's lab
section never showed it; "ECOG Performance Status score" matches no biomarker
keyword, so that section never showed it either. The score was parsed and
silently dropped before the prompt was built -- and ECOG 0-1 or 0-2 is the
single most common gate in interventional oncology, so every one of those
criteria came back not_evaluable for every patient.

Covers:
    1. _parse_ecog_observation reads BOTH value shapes -- valueInteger (the
       mCODE form written by File 04's normalizer) and valueQuantity (what
       Synthea's exporter actually emits, with UCUM "{score}") -- and records
       which one it found.
    2. It RAISES on a non-integral value, an out-of-range grade, an absent
       value[x], and an unreadable value[x] shape. Rounding 1.5 to 2 would
       invent a grade the record does not contain.
    3. _select_ecog_performance_status takes the most recent observation dated
       on or before get_age_reference_date() -- never datetime.now() -- and
       records how many were found, how they partitioned, and which path
       produced the answer.
    4. Absence is distinct from a score of 0, in the field, in the hash, and in
       the prompt text. ECOG 0 is FULLY ACTIVE: the most eligible a patient can
       be, and exactly the value a truthiness test would erase.
    5. compute_patient_hash (File 13) includes ECOG, so its docstring promise --
       identical hash means identical input -- still holds once patients carry
       a score. A bundle with no ECOG hashes exactly as it did before the field
       existed, so already-logged hashes stay comparable.
    6. _create_patient_summary emits a named Performance Status line.
    7. END TO END on the scratch corpus generated by '04- FHIR Generate Data.py'
       (item: Generate ECOG performance status in Synthea): real bundles are
       parsed, the field is populated, 89247-1 never appears in the general
       observation pool, and _create_patient_summary is called directly on the
       parsed patients.
    8. STRUCTURAL -- _create_patient_summary touches neither the OpenAI client
       nor the Qdrant client, so section 7 proves the summary text without a
       single network call.

No network and no LLM. File 13 is loaded (its registries are local files and
its BM25 model is a local FastEmbed cache), but no OpenAI or Qdrant call is
made: the only File 13 functions invoked are compute_patient_hash and
_create_patient_summary, both pure.

Run from terminal (or F5 in Spyder):
    python "39- ECOG Performance Status Surfacing Test.py"

Exit codes:
    0 -- all assertions passed
    1 -- one or more failures
"""


# Run needed file
#----------------
# Item 20a: this file sits in the code directory, so __file__ locates it with
# no hardcoded path. __file__ is bound when the file is run as a script (every
# documented entry point for it) and when Spyder runfile()s it. In a bare
# interactive paste it is not bound, and the working directory is the only
# remaining candidate -- taken, but announced, never silently.
import os as _os_boot
if "__file__" in globals():
    _code_dir = _os_boot.path.dirname(_os_boot.path.abspath(__file__)) + _os_boot.sep
else:
    _code_dir = _os_boot.getcwd() + _os_boot.sep
    print(f"[Bootstrap] __file__ unbound; using the working directory as the code directory: {_code_dir}")
del _os_boot

for _bootstrap in ("01- Imports.py", "02- Utility Functions.py"):
    with open(_code_dir + _bootstrap) as _fh:
        exec(_fh.read(), globals())

# 13 chains 03, 08, 09 and 10 itself -- they are NOT listed here. 07 is loaded
# after it; the two files share no top-level name, so neither shadows the other.
exec_chain(
    ["13- LangGraph Agent.py", "07- FHIR Parser.py"],
    caller_file=_code_dir + "39- ECOG Performance Status Surfacing Test.py",
    caller_globals=globals(),
    chain_label="01 → 02 → 13 → 07",
)


#------------------------------------------------------------------------------


import ast
import shutil
import tempfile
import textwrap


# Scratch corpus written by '04- FHIR Generate Data.py --output-dir ...'.
# Resolved from data_patient_path, never written as an absolute path.
_SCRATCH_FHIR_DIR = data_patient_path + "scratch_ecog/fhir/"


# ===========================================================================
# MINIMAL ASSERTION HARNESS
# ===========================================================================

_RESULTS = {"passed": 0, "failed": 0}
_FAILURES = []


def check(label: str, actual, expected) -> None:
    """Assert equality, record the outcome, never abort the run."""
    if actual == expected:
        _RESULTS["passed"] += 1
        print(f"  PASS  {label}")
    else:
        _RESULTS["failed"] += 1
        _FAILURES.append(
            f"{label}\n          expected: {expected}\n          actual:   {actual}"
        )
        print(f"  FAIL  {label}")
        print(f"          expected: {expected}")
        print(f"          actual:   {actual}")


def check_raises(label: str, fn, exc_type=ValueError):
    """Pass if fn() raises exc_type; fail if it returns or raises anything else.

    "Refused the value" is the assertion here, not a side effect of one: the
    defect being guarded against is a bad grade being quietly rounded or
    defaulted into the record.
    """
    try:
        value = fn()
    except exc_type as exc:
        _RESULTS["passed"] += 1
        print(f"  PASS  {label}  ({type(exc).__name__})")
        return exc
    except Exception as exc:
        _RESULTS["failed"] += 1
        _FAILURES.append(
            f"{label}\n          expected {exc_type.__name__}, "
            f"raised {type(exc).__name__}: {exc}"
        )
        print(f"  FAIL  {label}  (raised {type(exc).__name__}: {exc})")
        return None
    _RESULTS["failed"] += 1
    _FAILURES.append(f"{label}\n          did not raise; returned {value!r}")
    print(f"  FAIL  {label}  (did not raise; returned {value!r})")
    return None


def _ecog_resource(value_block: dict, date: str = "2020-06-28T13:49:49-07:00") -> dict:
    """A minimal but realistic ECOG Observation, shaped like Synthea's export."""
    resource = {
        "resourceType": "Observation",
        "status": "final",
        "category": [{"coding": [{
            "system": "http://terminology.hl7.org/CodeSystem/observation-category",
            "code": "survey", "display": "Survey"}]}],
        "code": {"coding": [{
            "system": "http://loinc.org",
            "code": "89247-1",
            "display": "ECOG Performance Status score"}]},
        "subject": {"reference": "urn:uuid:patient"},
        "encounter": {"reference": "urn:uuid:encounter"},
    }
    if date is not None:
        resource["effectiveDateTime"] = date
    resource.update(value_block)
    return resource


def _patient(ecog_status=None, **overrides) -> dict:
    """A minimal parsed-patient dict of the shape File 07 returns."""
    patient = {
        "patient_id": "test-patient",
        "demographics": {"birth_date": "1960-04-12", "age": 65, "sex": "female",
                         "race": "White", "ethnicity": "Not Hispanic or Latino"},
        "conditions": [{"display": "Malignant neoplasm of breast", "code": "254837009",
                        "onset_date": "2019-02-01", "clinical_status": "active",
                        "verification_status": "confirmed", "codings": []}],
        "medications": [],
        "observations": [],
        "procedures": [],
        "allergies": [],
        "cancer_stage_observations": [],
        "cancer_genomic_variants": [],
        "ecog_performance_status": ecog_status,
    }
    patient.update(overrides)
    return patient


_REFERENCE_DATE = get_age_reference_date().isoformat()


# ===========================================================================
# 1. VALUE SHAPES -- valueInteger AND valueQuantity
# ===========================================================================

print("\n" + "=" * 70)
print("1. _parse_ecog_observation reads both value shapes")
print("=" * 70)

_integer_form = _parse_ecog_observation(_ecog_resource({"valueInteger": 1}))
check("valueInteger value", _integer_form["value"], 1)
check("valueInteger shape recorded", _integer_form["value_shape"], "valueInteger")
check("valueInteger carries no unit", _integer_form["unit"], None)
check("valueInteger date preserved",
      _integer_form["date"], "2020-06-28T13:49:49-07:00")

_quantity_form = _parse_ecog_observation(_ecog_resource({
    "valueQuantity": {"value": 2, "unit": "{score}",
                      "system": "http://unitsofmeasure.org", "code": "{score}"}
}))
check("valueQuantity value", _quantity_form["value"], 2)
check("valueQuantity shape recorded", _quantity_form["value_shape"], "valueQuantity")
check("valueQuantity unit preserved", _quantity_form["unit"], "{score}")

# Synthea's PlainBigDecimal can serialise an integral grade as 3.0.
_float_form = _parse_ecog_observation(_ecog_resource({
    "valueQuantity": {"value": 3.0, "unit": "{score}"}}))
check("integral float accepted as int", _float_form["value"], 3)
check("integral float returns an int, not a float",
      isinstance(_float_form["value"], int), True)

check("grade 0 parses as 0",
      _parse_ecog_observation(_ecog_resource({"valueInteger": 0}))["value"], 0)
check("grade 5 is accepted by the parser (real records may carry it)",
      _parse_ecog_observation(_ecog_resource({"valueInteger": 5}))["value"], 5)

check("effectivePeriod.start is used when effectiveDateTime is absent",
      _parse_ecog_observation({
          "resourceType": "Observation",
          "code": {"coding": [{"system": "http://loinc.org", "code": "89247-1"}]},
          "effectivePeriod": {"start": "2021-05-05"},
          "valueInteger": 1,
      })["date"], "2021-05-05")


# ===========================================================================
# 2. BAD VALUES RAISE -- never rounded, never defaulted
# ===========================================================================

print("\n" + "=" * 70)
print("2. Non-integral and out-of-range values raise")
print("=" * 70)

check_raises("fractional grade 1.5 raises rather than rounding to 2",
             lambda: _parse_ecog_observation(_ecog_resource(
                 {"valueQuantity": {"value": 1.5, "unit": "{score}"}})))
check_raises("grade 6 (above the ECOG scale) raises",
             lambda: _parse_ecog_observation(_ecog_resource({"valueInteger": 6})))
check_raises("grade -1 raises",
             lambda: _parse_ecog_observation(_ecog_resource({"valueInteger": -1})))
check_raises("no value[x] at all raises",
             lambda: _parse_ecog_observation(_ecog_resource({})))
check_raises("valueQuantity with a null value raises",
             lambda: _parse_ecog_observation(_ecog_resource(
                 {"valueQuantity": {"unit": "{score}"}})))
check_raises("valueString raises rather than being coerced",
             lambda: _parse_ecog_observation(_ecog_resource({"valueString": "1"})))
check_raises("valueCodeableConcept raises (not mCODE-legal for this profile)",
             lambda: _parse_ecog_observation(_ecog_resource(
                 {"valueCodeableConcept": {"coding": [
                     {"system": "http://loinc.org", "code": "LA9623-5",
                      "display": "Restricted in strenuous activity"}]}})))
check_raises("valueBoolean raises",
             lambda: _parse_ecog_observation(_ecog_resource({"valueBoolean": True})))


# ===========================================================================
# 3. SELECTION -- most recent at or before the age reference date
# ===========================================================================

print("\n" + "=" * 70)
print("3. Most recent on or before the reference date wins")
print("=" * 70)

_ref = get_age_reference_date()
_before_1 = {"value": 0, "value_shape": "valueInteger", "unit": None,
             "date": "2019-01-01", "loinc": "89247-1"}
_before_2 = {"value": 2, "value_shape": "valueInteger", "unit": None,
             "date": "2024-06-15", "loinc": "89247-1"}
_before_3 = {"value": 1, "value_shape": "valueInteger", "unit": None,
             "date": "2021-03-03", "loinc": "89247-1"}
# DERIVED, not literal. This fixture's whole job is to sit AFTER the reference
# date, and the reference date is DATA_SNAPSHOT_DATE (03- Config.py), which
# moves every time the corpus is regenerated. It was "2026-05-14", chosen when
# DATA_SNAPSHOT_DATE was 2026-03-11; item 18b moved the constant to 2026-08-03
# and the fixture silently became a BEFORE observation, failing eight
# assertions in this section on behaviour that was entirely correct.
#
# One day past the reference is the minimal "after" and exercises the boundary
# rather than a date far from it. date.fromordinal(...+1) rather than
# timedelta: 01- Imports.py imports `date` but not `timedelta`.
_AFTER_REFERENCE_DATE = date.fromordinal(_ref.toordinal() + 1).isoformat()

_after = {"value": 4, "value_shape": "valueInteger", "unit": None,
          "date": _AFTER_REFERENCE_DATE, "loinc": "89247-1"}
_undated = {"value": 3, "value_shape": "valueInteger", "unit": None,
            "date": "unknown", "loinc": "89247-1"}

_none = _select_ecog_performance_status([])
check("no observations -> value None", _none["value"], None)
check("no observations -> selection", _none["selection"], "none_recorded")
check("no observations -> count 0", _none["observations_found"], 0)
check("reference date is the snapshot date, not the clock",
      _none["reference_date"], DATA_SNAPSHOT_DATE)

_multi = _select_ecog_performance_status([_before_1, _before_2, _before_3])
check("most recent of three wins", _multi["value"], 2)
check("its date is carried", _multi["date"], "2024-06-15")
check("count of all observations found", _multi["observations_found"], 3)
check("count on or before reference", _multi["observations_on_or_before_reference"], 3)
check("selection path", _multi["selection"], "most_recent_on_or_before_reference_date")

_mixed = _select_ecog_performance_status([_before_1, _after, _before_2])
check("an observation after the reference date is not chosen", _mixed["value"], 2)
check("but it IS counted", _mixed["observations_found"], 3)
check("and counted as after-reference", _mixed["observations_after_reference"], 1)

_only_after = _select_ecog_performance_status([_after])
check("only-after-reference -> value None", _only_after["value"], None)
check("only-after-reference -> still counted", _only_after["observations_found"], 1)
check("only-after-reference -> selection names the reason",
      _only_after["selection"], "all_after_reference_date")

_one_undated = _select_ecog_performance_status([_undated])
check("a lone undated observation is used", _one_undated["value"], 3)
check("and the path says so", _one_undated["selection"], "undated_single")

_two_undated = _select_ecog_performance_status([_undated, dict(_undated, value=1)])
check("several undated observations are refused, not guessed between",
      _two_undated["value"], None)
check("and the path says so", _two_undated["selection"], "undated_ambiguous")
check("both are still counted", _two_undated["observations_undated"], 2)

# Determinism on a tie: same date, different values. sorted() is stable, so the
# later entry in bundle order wins, and it wins the same way on every run.
_tie_a = dict(_before_2, value=2)
_tie_b = dict(_before_2, value=3)
check("tied dates resolve deterministically (last in bundle order)",
      _select_ecog_performance_status([_tie_a, _tie_b])["value"], 3)
check("and the same way when re-run",
      _select_ecog_performance_status([_tie_a, _tie_b])["value"], 3)


# ===========================================================================
# 4. ABSENCE IS NOT ZERO
# ===========================================================================

print("\n" + "=" * 70)
print("4. Absence is distinguishable from a score of 0")
print("=" * 70)

_scored_zero = _select_ecog_performance_status([_before_1])   # ECOG 0
_absent = _select_ecog_performance_status([])

check("scored 0 -> value is 0", _scored_zero["value"], 0)
check("scored 0 -> value is NOT None", _scored_zero["value"] is None, False)
check("absent -> value IS None", _absent["value"] is None, True)
check("the two differ", _scored_zero["value"] == _absent["value"], False)
check("absent never defaults to 0", _absent["value"] == 0, False)
check("scored 0 has an observation count", _scored_zero["observations_found"], 1)
check("absent has none", _absent["observations_found"], 0)


# ===========================================================================
# 5. compute_patient_hash
# ===========================================================================

print("\n" + "=" * 70)
print("5. compute_patient_hash covers ECOG")
print("=" * 70)

_p_absent = _patient(_absent)
_p_zero   = _patient(_scored_zero)
_p_one    = _patient(_select_ecog_performance_status([_before_3]))
_p_unusable = _patient(_only_after)

check("hashing is deterministic",
      compute_patient_hash(_p_zero), compute_patient_hash(_patient(_scored_zero)))
check("ECOG 0 and no ECOG hash differently",
      compute_patient_hash(_p_zero) == compute_patient_hash(_p_absent), False)
check("ECOG 0 and ECOG 1 hash differently",
      compute_patient_hash(_p_zero) == compute_patient_hash(_p_one), False)

# An ECOG that exists but postdates the snapshot is NOT the same input as no
# ECOG at all, even though both resolve to value None.
check("present-but-unusable differs from absent",
      compute_patient_hash(_p_unusable) == compute_patient_hash(_p_absent), False)

# Backward compatibility: a bundle with no ECOG must hash exactly as it did
# before this field existed, or every hash already in inferences.db becomes
# incomparable in order to record "still nothing".
_p_legacy = _patient()
del _p_legacy["ecog_performance_status"]
check("a patient with no ECOG hashes as it did before the field existed",
      compute_patient_hash(_p_absent), compute_patient_hash(_p_legacy))
check("a missing key and an empty status agree",
      compute_patient_hash(_patient(None)), compute_patient_hash(_p_legacy))


# ===========================================================================
# 6. PATIENT SUMMARY -- its own named line
# ===========================================================================

print("\n" + "=" * 70)
print("6. _create_patient_summary emits a named Performance Status line")
print("=" * 70)

_sum_one = _create_patient_summary(_p_one)
check("section header present", "Performance Status:" in _sum_one, True)
check("value on its own named line",
      "- ECOG performance status: 1 (2021-03-03)" in _sum_one, True)

_sum_zero = _create_patient_summary(_p_zero)
check("ECOG 0 is rendered as 0, not swallowed by a truthiness test",
      "- ECOG performance status: 0 (2019-01-01)" in _sum_zero, True)
check("ECOG 0 is not reported as missing",
      "not recorded" in _sum_zero.split("Conditions:")[0], False)

_sum_absent = _create_patient_summary(_p_absent)
check("absence is stated explicitly",
      "- ECOG performance status: not recorded" in _sum_absent, True)

_sum_unusable = _create_patient_summary(_p_unusable)
check("present-but-unusable is not reported as 'not recorded'",
      "not recorded" in _sum_unusable.split("Conditions:")[0], False)
check("present-but-unusable states the count",
      "1 observation(s) on file" in _sum_unusable, True)
check("present-but-unusable names the reason",
      "all_after_reference_date" in _sum_unusable, True)

_sum_multi = _create_patient_summary(_patient(_multi))
check("the count is shown when more than one was eligible",
      "most recent of 3" in _sum_multi, True)

# The count must be of the pool the winner was drawn from. _mixed has three
# observations but only two are on or before the snapshot, and the third is
# LATER than the one reported -- "most recent of 3" would be false.
_sum_mixed = _create_patient_summary(_patient(_mixed))
check("excluded observations are not counted into 'most recent of N'",
      "most recent of 2" in _sum_mixed, True)
check("and they are disclosed rather than dropped",
      "1 further observation(s) outside the" in _sum_mixed, True)

check("the summary of a scored patient differs from an unscored one",
      _sum_zero == _sum_absent, False)


# ===========================================================================
# 7. END TO END on the scratch corpus
# ===========================================================================

print("\n" + "=" * 70)
print("7. END TO END -- real scratch bundles from File 04")
print("=" * 70)

_scratch = Path(_SCRATCH_FHIR_DIR)
if not _scratch.is_dir():
    _RESULTS["failed"] += 1
    _FAILURES.append(
        f"scratch corpus not found at {_SCRATCH_FHIR_DIR}\n"
        f"          Generate it first:\n"
        f'          python "04- FHIR Generate Data.py" --population 3000 '
        f'--seed 20260803 --output-dir <data_patient_path>/scratch_ecog'
    )
    print(f"  FAIL  scratch corpus not found at {_SCRATCH_FHIR_DIR}")
else:
    ECOG_VALUE_SHAPE_COUNTS.clear()
    ECOG_SELECTION_COUNTS.clear()

    _scored, _unscored, _unusable_real = [], [], []
    _pool_leak = 0
    _bundles = 0

    for _path in sorted(_scratch.glob("*.json")):
        _raw = _path.read_text(encoding="utf-8")
        if '"89247-1"' not in _raw and '"resourceType": "Patient"' not in _raw:
            continue
        _parsed = parse_fhir_bundle(str(_path))
        if _parsed.get("patient_id") is None:
            continue          # hospitalInformation / practitionerInformation
        _bundles += 1

        _status = _parsed["ecog_performance_status"]

        # The routing claim: 89247-1 must never remain in the general pool.
        if any(o.get("code") == "89247-1" for o in _parsed["observations"]):
            _pool_leak += 1

        if _status["value"] is not None:
            _scored.append((_path.name, _parsed, _status))
        elif _status["observations_found"]:
            _unusable_real.append((_path.name, _parsed, _status))
        else:
            _unscored.append((_path.name, _parsed, _status))

    print(f"  parsed {_bundles} patient bundles: {len(_scored)} scored, "
          f"{len(_unusable_real)} present-but-unusable, {len(_unscored)} unscored")
    print(f"  value shapes:    {dict(sorted(ECOG_VALUE_SHAPE_COUNTS.items()))}")
    print(f"  selection paths: {dict(sorted(ECOG_SELECTION_COUNTS.items()))}")

    check("the field is present on every parsed patient",
          all(isinstance(p["ecog_performance_status"], dict)
              for _, p, _s in _scored + _unscored + _unusable_real), True)
    check("89247-1 never leaks into patient_data['observations']", _pool_leak, 0)
    check("the scratch corpus yields scored patients", len(_scored) > 0, True)
    check("it also yields unscored patients (absence is representable)",
          len(_unscored) > 0, True)
    check("every scored value is an int in 0-4",
          all(isinstance(s["value"], int) and 0 <= s["value"] <= 4
              for _, _, s in _scored), True)
    check("no scored patient carries grade 5",
          any(s["value"] == 5 for _, _, s in _scored), False)
    check("the corpus is normalized, so every shape is valueInteger",
          dict(ECOG_VALUE_SHAPE_COUNTS), {"valueInteger": len(_scored) + len(_unusable_real)})
    check("unscored patients report a count of 0",
          all(s["observations_found"] == 0 for _, _, s in _unscored), True)

    # The summary, built directly from real parsed patients. No Qdrant, no OpenAI.
    _name, _real_patient, _real_status = _scored[0]
    _real_summary = _create_patient_summary(_real_patient)
    check("real scored patient: named ECOG line in the summary",
          f"- ECOG performance status: {_real_status['value']} (" in _real_summary, True)
    check("real scored patient: line sits under the Performance Status header",
          _real_summary.split("Performance Status:\n")[1].startswith(
              "- ECOG performance status:"), True)

    _real_unscored_summary = _create_patient_summary(_unscored[0][1])
    check("real unscored patient: absence stated, not defaulted to 0",
          "- ECOG performance status: not recorded" in _real_unscored_summary, True)

    check("every scored patient renders its value into the summary",
          all(f"- ECOG performance status: {s['value']} (" in _create_patient_summary(p)
              for _, p, s in _scored[:25]), True)

    # Whether any real observation postdates the reference depends on the gap
    # between the corpus's generation date and DATA_SNAPSHOT_DATE, so this
    # block is CONDITIONAL and neither outcome is a failure.
    #
    # It stated "this corpus was generated on 2026-08-03 while
    # DATA_SNAPSHOT_DATE is 2026-03-11" -- true when written, false as soon as
    # item 18b set the constant to the generation date. Naming the current
    # value of a constant in a comment is the same defect this file's _after
    # fixture had: a literal that expires silently.
    #
    # When the corpus is generated ON the snapshot date -- the normal case
    # after a regeneration -- nothing postdates it, _unusable_real is empty,
    # and the else branch reports that rather than asserting on nothing.
    if _unusable_real:
        _uname, _upatient, _ustatus = _unusable_real[0]
        check("real present-but-unusable patient names the reason",
              _ustatus["selection"], "all_after_reference_date")
        check("real present-but-unusable patient keeps value None",
              _ustatus["value"], None)
        check("and its summary does not say 'not recorded'",
              "not recorded" in _create_patient_summary(_upatient).split("Conditions:")[0],
              False)
    else:
        print("  NOTE  no scratch observation postdates the reference date; "
              "the after-reference path is covered synthetically in section 3 only")

    # Hashes must actually differ across real patients with different scores.
    _by_value = {}
    for _n, _p, _s in _scored:
        _by_value.setdefault(_s["value"], _p)
    if len(_by_value) >= 2:
        _vals = sorted(_by_value)
        _h = {v: compute_patient_hash(_by_value[v]) for v in _vals}
        check("real patients with different ECOG scores hash differently",
              len(set(_h.values())), len(_vals))

    # ---- valueQuantity end to end -------------------------------------------
    # The scratch corpus has been through File 04's normalizer, so every value
    # is already an integer. Revert one bundle to the raw Synthea shape and
    # re-parse it: a bundle that has NOT been normalized must still parse, and
    # must yield the same score.
    _tmp_dir = tempfile.mkdtemp(prefix="ecog_shape_test_")
    try:
        _tmp_bundle = Path(_tmp_dir) / _name
        _doc = json.loads(Path(_scratch / _name).read_text(encoding="utf-8"))
        _reverted = 0
        for _entry in _doc.get("entry", []):
            _res = _entry.get("resource", {})
            if _res.get("resourceType") != "Observation":
                continue
            if not any(c.get("code") == "89247-1"
                       for c in _res.get("code", {}).get("coding", [])):
                continue
            _res["valueQuantity"] = {
                "value": _res.pop("valueInteger"),
                "unit": "{score}",
                "system": "http://unitsofmeasure.org",
                "code": "{score}",
            }
            _reverted += 1
        _tmp_bundle.write_text(json.dumps(_doc, indent=2), encoding="utf-8")

        check("test fixture reverted at least one observation", _reverted > 0, True)

        ECOG_VALUE_SHAPE_COUNTS.clear()
        _reparsed = parse_fhir_bundle(str(_tmp_bundle))
        _rstatus = _reparsed["ecog_performance_status"]

        check("un-normalized bundle still parses to the same score",
              _rstatus["value"], _real_status["value"])
        check("and reports the raw shape it actually found",
              _rstatus["value_shape"], "valueQuantity")
        check("and carries the UCUM annotation unit", _rstatus["unit"], "{score}")
        check("the shape counter saw valueQuantity",
              dict(ECOG_VALUE_SHAPE_COUNTS), {"valueQuantity": _reverted})
        check("the summary is identical either way",
              _create_patient_summary(_reparsed), _real_summary)
        # Same score, same date, byte-identical prompt text -- so the hash must
        # match. value_shape is recorded on the field but deliberately kept OUT
        # of the hash: if running File 04's normalizer over a corpus changed
        # every ECOG patient's hash, the ablation study would read a serialisation
        # change as an input change and report a difference that does not exist.
        check("normalizing a corpus does not change the hash",
              compute_patient_hash(_reparsed), compute_patient_hash(_real_patient))
        check("even though the recorded value_shape differs",
              _rstatus["value_shape"] == _real_status["value_shape"], False)
    finally:
        shutil.rmtree(_tmp_dir, ignore_errors=True)


# ===========================================================================
# 8. STRUCTURAL -- the summary path makes no network call
# ===========================================================================

print("\n" + "=" * 70)
print("8. STRUCTURAL -- no OpenAI or Qdrant call in the proven path")
print("=" * 70)

# inspect.getsource() cannot be used: every project file is exec()'d into this
# namespace under the shared-globals chain, so its functions have no source file
# to read back. The source is read off disk and sliced with ast instead.
def _function_source(filename: str, function_name: str) -> str:
    """Source of one top-level function's BODY, docstring excluded.

    The docstring is dropped because these checks are greps for forbidden call
    sites, and a docstring that explains why a call is forbidden contains the
    very string being searched for. Grepping the whole function makes the
    comment that documents the rule indistinguishable from a violation of it.
    """
    text = Path(_code_dir + filename).read_text(encoding="utf-8")
    for node in ast.parse(text).body:
        if not (isinstance(node, ast.FunctionDef) and node.name == function_name):
            continue
        body = node.body
        if (body and isinstance(body[0], ast.Expr)
                and isinstance(body[0].value, ast.Constant)
                and isinstance(body[0].value.value, str)):
            body = body[1:]
        return "\n".join(
            ast.get_source_segment(text, stmt) or "" for stmt in body
        )
    raise AssertionError(f"{function_name} not found at top level of {filename}")


# RETARGETED IN PASS 20c-2b. The parser's definitions moved to
# oncotriage/fhir/parser.py and "07- FHIR Parser.py" is now a re-export shim, so
# every path below that named the numbered file names the module instead.
#
# THIS IS NOT COSMETIC. _function_source() RAISES AssertionError when it cannot
# find the function, so a stale filename here would have aborted the run rather
# than passing silently -- but only for the two direct calls further down. The
# loop below would have hit the same raise on its third item, so the fourth
# never runs. Either way the checks stop being performed, and the fix is to
# point at the file the definitions are actually in.
#
# _function_source() prefixes _code_dir, so a package-relative path works
# unchanged; the separator is forward-slash because that is what os.path.join
# would produce here anyway and this string is only ever concatenated.
_PARSER_MODULE = os.path.join("oncotriage", "fhir", "parser.py")

# RETARGETED AGAIN IN PASS 20c-2c. Both File 13 entries moved: the agent is
# oncotriage/agent/ now, and both of these functions live in patient.py.
#
# THIS ONE FAILS LOUDLY RATHER THAN GREEN, and that is a property of
# _function_source(), not luck: it RAISES AssertionError when the function is
# not at top level of the file it was given. Against the shim the loop below
# would have aborted on its first item and taken the rest of this section with
# it. The non-degeneracy check under the loop is added anyway, because the
# checks themselves are all "this string is ABSENT", which an empty body
# satisfies.
_PATIENT_MODULE = os.path.join("oncotriage", "agent", "patient.py")

_PROVEN_PATH = (
    (_PATIENT_MODULE, "_create_patient_summary"),
    (_PATIENT_MODULE, "compute_patient_hash"),
    (_PARSER_MODULE,  "_parse_ecog_observation"),
    (_PARSER_MODULE,  "_select_ecog_performance_status"),
)

for _file, _fn_name in _PROVEN_PATH:
    _src = _function_source(_file, _fn_name)
    # NON-DEGENERATE FIRST: both checks below are "this string is absent", and
    # an empty body satisfies both.
    check(f"{_fn_name}: the sliced source is substantial (non-degeneracy)",
          len(_src) > 400, True)
    check(f"{_fn_name} does not touch the OpenAI client",
          "openai_client" in _src, False)
    check(f"{_fn_name} does not touch the Qdrant client",
          "qdrant_client" in _src, False)

_sel_src = _function_source(_PARSER_MODULE, "_select_ecog_performance_status")
# NON-DEGENERATE. Two of the three checks on this source are "the string is
# absent", which an empty source satisfies for free -- and an empty source is
# what _function_source() returns for a function whose body is a docstring and
# nothing else. It is not, and this says so before anything is inferred from
# its contents.
check("the sliced selection source is substantial (non-degeneracy)",
      len(_sel_src) > 500, True)
check("selection uses get_age_reference_date, not the clock",
      "get_age_reference_date" in _sel_src, True)
check("selection contains no now()/today() call",
      ("datetime.now" in _sel_src) or ("date.today" in _sel_src), False)

# The routing itself: 89247-1 must be matched explicitly in parse_fhir_bundle,
# not left to fall through to the general observation pool.
_bundle_src = _function_source(_PARSER_MODULE, "parse_fhir_bundle")
check("parse_fhir_bundle routes the ECOG LOINC explicitly",
      "_ECOG_LOINC_CODE" in _bundle_src, True)
check("and calls the ECOG parser rather than _parse_observation",
      "_parse_ecog_observation" in _bundle_src, True)


# ===========================================================================
# SUMMARY
# ===========================================================================

print("\n" + "=" * 70)
print("SUMMARY")
print("=" * 70)
print(f"Passed: {_RESULTS['passed']}")
print(f"Failed: {_RESULTS['failed']}")

if _FAILURES:
    print("\nFailures:")
    for _f in _FAILURES:
        print(textwrap.indent(f"  - {_f}", ""))

if __name__ == "__main__":
    sys.exit(1 if _RESULTS["failed"] else 0)


#------------------------------------------------------------------------------


#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Aug  3 2026

@author: ramyalsaffar
"""
