# Create DAG
############

"""Generate the ``trial_refresh_weekly`` Airflow DAG and write it to disk.

Moved out of "23- Airflow DAG.py" by item 20c, pass 3c-2. That file is now a
thin entry point: a ``__main__`` guard and one call.

THE OUTPUT OF THIS MODULE IS THE ARTEFACT, NOT THIS MODULE
-----------------------------------------------------------
The scheduler parses ``{airflow_path}/dags/trial_refresh_weekly.py``. It never
sees this file. So the only thing that matters about this move is that the
generated TEXT is unchanged, and pass 3c-2 proved that by generating from git
HEAD's File 23 into one temporary directory, generating from this module into
another, and comparing sha256. They match: the DAG text is byte-identical.

THE TWO STALE PROSE LINES ARE FIXED (pass 20f-3), AND THE ACCEPTANCE CRITERION
IS THE OPPOSITE ONE. The generated text used to say "03- Config.py" in two
places -- the DAG module docstring's Schedule line and the comment above
DAG_SCHEDULE -- while the code beneath both of them opened
``oncotriage/config.py``, which is what item 20c retargeted them to. Pass 3c-2
left them wrong on purpose: correcting a character would have changed the bytes
and made ITS equivalence proof meaningless, so it recorded a one-line follow-up
"whose acceptance criterion is a NEW sha256". Pass 20e then DELETED
``03- Config.py`` outright, so the generated DAG named a file that does not
exist -- prose pointing an operator at nothing.

So this pass had to produce a new sha256, and did: the deployed DAG went from
20,542 bytes / ``68963b0c...`` to the size and digest recorded in CLAUDE.md,
regenerated by deleting the file and re-running "23- Airflow DAG.py", and
Airflow's own ``DagBag`` was asked to parse the result rather than the parse
being assumed.

WHY dag_content IS A FUNCTION NOW
---------------------------------
File 23 assembled ``dag_content`` at MODULE LEVEL, and the middle third of it is
``%``-formatted with three resolved paths -- ``code_path``, ``keys_path`` and
``data_trial_path``. Reading any of those fires ``oncotriage.paths``' lazy
resolver, which globs the sibling directory tree. So importing this module, had
the assembly stayed at module level, would have resolved three directories and
raised on any machine without them. ``build_dag_content()`` is the fix; the head
and the tail stay module-level constants because they are plain strings that
resolve nothing.

Note which half of File 23's item-20b comment survives that. It said "dag_content
itself stays at module level -- it is a string, building it touches nothing".
The first clause was right and the second was not: building it read three lazy
paths. Under the exec chain that was invisible, because "01- Imports.py" had
already resolved every path before File 23 was reached.

WHAT IMPORTING THIS MODULE DOES
-------------------------------
Binds three string constants and four functions. It resolves no path, reads no
file, creates no directory and writes nothing. ``oncotriage.paths`` and
``oncotriage.settings`` are imported as MODULES -- a ``from X import name``
against ``paths`` is an attribute read and would fire the lazy resolver at
import.

THE DAG NO LONGER DUPLICATES THE SCRAPE OR THE INDEX BUILD
----------------------------------------------------------
It used to, and the previous version of this paragraph recorded that as "a
known cost rather than a discovery" and deferred the fix. The cost came due:
the copies HAD drifted, in every direction at once, and the generated DAG
built a materially worse index than ``11- RAG Trial Indexer.py`` -- no sparse
vectors at all, no payload index, no conditionsModule, a splitter whose
inclusion marker ``"patients must"`` is a prefix of its own exclusion marker
``"patients must not"``, one embedding API call per trial, the same exactly-18
age filter, and a verify step that ran after the alias swap.

The generated tasks now call ``oncotriage.retrieval.indexer`` directly. The
import is DEFERRED INTO EACH TASK -- never at module scope -- so the
scheduler's continuous re-parse of the dags folder cannot be broken by an
environment that lacks the package; only an actual run fails, and it fails
naming the path it tried. That is the trade the old copies were avoiding, and
it is the right one: a DAG that will not run is visible, a DAG that runs and
promotes a sparse-vector-less collection is not.
"""

from pathlib import Path

from oncotriage import paths
from oncotriage import settings as path_settings
from oncotriage.orchestration.home import resolve_airflow_home
from oncotriage.observability import console


#------------------------------------------------------------------------------


# DAG file content (head + generated path block + tail — see the path block below)
dag_content_head = '''"""
Weekly Trial Refresh DAG

Scrapes clinical trials, rebuilds Qdrant index.
Schedule: read from AIRFLOW_DAG_SCHEDULE in oncotriage/config.py (None = no
automatic runs; the DAG stays registered and manually triggerable).

Airflow 3.1.7 | TaskFlow API | Pure Python (no BashOperator)
"""

import ast
import os
import sys
import json
import time
import re
import hashlib
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List

import pendulum
from airflow.sdk import dag, task


# =============================================================================
# Escape-safe constants (avoids issues with triple-quoted string writing)
# =============================================================================
DIGIT_PATTERN = re.compile(chr(92) + "d+")       # matches \\d+ (digits)
NEWLINE_SEP = chr(10) + chr(10)                    # matches "\\n\\n" (double newline)
'''


# =============================================================================
# Project paths for the generated DAG  (item 20a)
# =============================================================================
# Airflow parses the generated DAG in the scheduler's own process, from
# {airflow_path}/dags/. That process has not run exec_chain and has none of
# 01- Imports.py's names, and the DAG file does not sit in the code directory,
# so it cannot find itself with __file__ either. Environment variables are the
# only mechanism that reaches it, and Airflow passes them through.
#
# The fallbacks are not literals in this file. They are whatever
# oncotriage.paths resolves at DAG-generation time, rendered in with repr(), so
# the generator and the generated file cannot drift.
#
# One value changes meaning as a result. KEYS_PATH used to be a literal
# ".../04- Keys/", a directory that does not exist -- the keys live in
# "05- Keys/", which is what the keys_path glob has always found. The
# generated DAG's _read_key() therefore raised FileNotFoundError on every run.
# Sourcing the fallback from the resolved path fixes that as a side effect; it
# is called out here because it is a behaviour change, not just a path move.
#
# dag_content is split in three around this block because it is a plain
# triple-quoted string, not an f-string: the DAG body contains dict literals
# and f-strings of its own, so neither .format() nor an f-prefix can be
# applied to it.
#
# PASS 3c-2 MADE THIS A FUNCTION. The template below is a module constant --
# it is a string and it resolves nothing -- but the three values interpolated
# into it are lazy paths, so the % had to move onto a call. See the module
# docstring.

_DAG_PATH_BLOCK_TEMPLATE = '''

# =============================================================================
# Project Paths (fallbacks resolved by 01- Imports.py when this file was
# generated; override any of them with the environment variable named beside
# it, which is how a container or a different checkout retargets this DAG)
# =============================================================================
def _path_from_env(var_name, fallback):
    """Environment variable if set to a non-empty value, else the fallback.

    An empty string counts as unset: `export ONCOTRIAGE_KEYS_PATH=` is a
    normal way to clear a variable, and taking it literally would turn every
    absolute path below into a relative one against the scheduler's working
    directory.
    """
    raw = os.environ.get(var_name)
    if raw is not None and raw.strip() != "":
        resolved = raw.strip().rstrip("/") + "/"
        print("[DAG paths] " + var_name + " -> " + resolved)
        return resolved
    return fallback


PROJECT_CODE_PATH = _path_from_env(%r, %r)
KEYS_PATH = _path_from_env(%r, %r)
DATA_TRIAL_PATH = _path_from_env(%r, %r)
'''


def build_path_block(code_path=None, keys_path=None, data_trial_path=None):
    """Render the middle third of the DAG: the three env-var-overridable paths.

    Args:
        code_path:       Fallback for ONCOTRIAGE_CODE_PATH. None resolves
                         ``oncotriage.paths.code_path`` ON THE CALL.
        keys_path:       Fallback for ONCOTRIAGE_KEYS_PATH. None resolves
                         ``oncotriage.paths.keys_path``.
        data_trial_path: Fallback for ONCOTRIAGE_DATA_TRIAL_PATH. None resolves
                         ``oncotriage.paths.data_trial_path``.

    Returns:
        The rendered block, byte-identical to what File 23 built at module
        level from the same three values.

    The three overrides exist so that a caller -- a test, or a machine
    generating a DAG for a different checkout -- can produce the text without
    resolving this machine's tree. The default path is the one File 23 took.
    """
    if code_path is None:
        code_path = paths.code_path
    if keys_path is None:
        keys_path = paths.keys_path
    if data_trial_path is None:
        data_trial_path = paths.data_trial_path

    return _DAG_PATH_BLOCK_TEMPLATE % (
        path_settings.ENV_CODE_PATH,       path_settings.with_trailing_sep(code_path),
        path_settings.ENV_KEYS_PATH,       path_settings.with_trailing_sep(keys_path),
        path_settings.ENV_DATA_TRIAL_PATH, path_settings.with_trailing_sep(data_trial_path),
    )


dag_content_tail = '''

# =============================================================================
# Config (read out of oncotriage/config.py, at parse time and at task time)
# =============================================================================
#
# ITEM 20c RETARGETED THIS, AND PASS 20e SETTLED IT. Both functions used to read
# a numbered file that no longer exists. Every constant moved into
# oncotriage/config.py; the numbered file became a shim that re-exported them
# with `from oncotriage.config import ...`, and pass 20e deleted the shim. Each
# step broke one of the old readers, and only one of them loudly:
#
#   _config_literal  looks for a module-level Assign. An ImportFrom is not an
#                    Assign, so against the shim it raised
#                    "AIRFLOW_DAG_SCHEDULE is not assigned at module level" at
#                    every DAG parse; against the deleted file it would be a
#                    FileNotFoundError.
#   _load_config     exec'd the shim, which needed the oncotriage package on the
#                    scheduler's sys.path -- a dependency the scheduler has no
#                    reason to satisfy, and one that surfaced as an ImportError
#                    inside a task rather than at generation.
#
# Both read oncotriage/config.py, which holds the literals themselves.
def _config_literal(name):
    """Read one module-level literal out of oncotriage/config.py without
    running it.

    Reading the assignment out of the AST needs no keys, no network and no
    sys.path entry for the package -- which is what makes it usable at DAG
    PARSE time, in the scheduler's own process.

    Raises if the name is absent. A schedule that cannot be read is a config
    defect, and defaulting to some other schedule here would silently restore
    automatic runs that were deliberately turned off.
    """
    config_path = PROJECT_CODE_PATH + "oncotriage/config.py"
    with open(config_path, "r") as f:
        tree = ast.parse(f.read(), filename=config_path)
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == name:
                    return ast.literal_eval(node.value)
    raise RuntimeError(f"{name} is not assigned at module level in {config_path}")


# THE EIGHTH ENTRY WAS DELETED WITH THE CONSTANT IT NAMED -- the Stage 4
# rerank floor, which was a floor on the fused RRF score and could never fire.
# Note what leaving it would have cost: _load_config runs INSIDE a task, and
# _config_literal RAISES when a name is not assigned at module level in
# oncotriage/config.py. So a DAG carrying a stale name parses clean, registers
# in the scheduler, shows healthy in the UI, and fails the weekly index refresh
# at run time with a message about a config file rather than about this DAG.
# Verified by running the previously-deployed DAG against the edited config: it
# imported fine and _load_config() raised.
#
# THIS ARGUMENT IS A `#` COMMENT AND NOT A DOCSTRING. The generated file is
# Python, and a deleted constant named inside a string literal is invisible to
# tests/test_package_invariants.py check 2h -- the scan that would report it if
# somebody reinstated the name. Same rule pass 20f-3 applied to its own
# deletions, applied here to the text this generator EMITS.
#
# FINDING, NOT FIXED HERE: six of the seven remaining entries are also dead.
# Only COLLECTION_NAME is read (twice, below). EMBEDDING_MODEL, EMBEDDING_DIM,
# MAX_TRIALS, TRIAL_CONDITION, TRIAL_STATUS and TRIAL_STUDY_TYPE are leftovers
# from the ~370-line inline scraper the admission pass deleted, and each is one
# config rename away from the same run-time failure. Removing them changes the
# generated bytes, which is its own item with its own new sha256.

def _load_config() -> dict:
    """The seven config values the tasks read as literals.

    This used to exec File 03 into a throwaway namespace, which built an
    OpenAI client and a Qdrant client as a side effect and therefore needed
    credentials inside an Airflow worker that has no other use for them. Every
    value below is a plain literal in oncotriage/config.py, so _config_literal
    serves all seven and nothing is constructed. The values are identical; what
    is gone is the exec.
    """
    trial_dict = _config_literal("trial_dict")
    return {
        "COLLECTION_NAME":    _config_literal("COLLECTION_NAME"),
        "EMBEDDING_MODEL":    _config_literal("EMBEDDING_MODEL"),
        "EMBEDDING_DIM":      _config_literal("EMBEDDING_DIM"),
        "MAX_TRIALS":         trial_dict["max_trials"],
        "TRIAL_CONDITION":    trial_dict["condition"],
        "TRIAL_STATUS":       trial_dict["status"],
        "TRIAL_STUDY_TYPE":   trial_dict["study_type"],
    }


# =============================================================================
# THE DAG NO LONGER CARRIES ITS OWN SCRAPER OR INDEXER
# =============================================================================
#
# It used to. Between this line and the task definitions there were ~370 lines
# reimplementing oncotriage/retrieval/indexer.py: _split_inclusion_exclusion,
# _parse_trial_metadata, _extract_locations, _create_trial_embedding_text, the
# scrape loop and the whole embed/upsert/swap sequence. They had ALREADY
# DIVERGED, and every difference made this DAG build a worse index than
# `python "11- RAG Trial Indexer.py"`:
#
#   * its inclusion markers were ["inclusion criteria:", "inclusion:",
#     "patients must"] -- and "patients must" is a PREFIX of the exclusion
#     marker "patients must not", so an exclusion heading matched both, the
#     two offsets came back equal, and the split collapsed to an EMPTY
#     exclusion section;
#   * its _parse_trial_metadata read no conditionsModule at all, so every
#     trial it wrote had no conditions, no keywords and no interventions --
#     which is what Stage 4's MeSH site filter and the conditions-bm25 channel
#     are built from;
#   * its collection was created with vectors_config ONLY. No
#     sparse_vectors_config, so none of title-bm25 / conditions-bm25 /
#     criteria-bm25 existed, and no payload index on nct_id was ever created.
#     All three of Stage 2's BM25 channels and every scroll-by-nct_id would
#     have failed against it;
#   * it embedded ONE TRIAL PER API CALL with time.sleep(0.1) between them;
#   * it carried the same `if min_age > 18: continue` exactly-18 filter;
#   * its verify step ran AFTER the alias swap, so it inspected a collection
#     that was already serving production.
#
# The DAG now delegates. There is ONE scraper and ONE indexer in this project,
# and this file no longer contains a second opinion about either.
#
# THE IMPORT IS INSIDE THE TASKS, NEVER AT MODULE SCOPE, and that is
# load-bearing. Airflow's scheduler re-parses every file in the dags folder
# continuously; a module-scope import that fails makes the DAG vanish from the
# UI with an import error. Deferred into the task, parsing is unaffected and
# only a RUN fails -- loudly, naming the path it tried.
def _package_indexer():
    """Import oncotriage.retrieval.indexer, or raise saying why not."""
    if CODE_PATH and CODE_PATH not in sys.path:
        sys.path.insert(0, CODE_PATH)
    try:
        from oncotriage.retrieval import indexer
    except ImportError as exc:
        raise RuntimeError(
            "trial_refresh_weekly delegates to oncotriage.retrieval.indexer and "
            "could not import it from " + repr(CODE_PATH) + ": " + str(exc) +
            ". Install the package into the Airflow environment "
            "(pip install -e <code dir>) or set " + repr("ONCOTRIAGE_CODE_PATH") +
            ". This DAG deliberately no longer carries its own copy of the "
            "scraper -- the copy had drifted and built a sparse-vector-less index."
        ) from exc
    return indexer


# =============================================================================
# DAG Definition
# =============================================================================
# Resolved once per scheduler parse. None means no timetable: the DAG is still
# registered and can be triggered by hand, it just never fires on its own.
# See the AIRFLOW_DAG_SCHEDULE block in oncotriage/config.py for why it is off.
DAG_SCHEDULE = _config_literal("AIRFLOW_DAG_SCHEDULE")


@dag(
    dag_id="trial_refresh_weekly",
    description="Weekly clinical trial index rebuild",
    schedule=DAG_SCHEDULE,
    start_date=pendulum.datetime(2026, 1, 1, tz="UTC"),
    catchup=False,
    default_args={
        "owner": "trialmatch",
        "depends_on_past": False,
        "retries": 2,
        "retry_delay": timedelta(minutes=5),
    },
    tags=["trialmatch", "production"],
)
def trial_refresh_weekly():

    @task(task_id="scrape_and_save")
    def scrape_and_save() -> str:
        """Scrape via the package's ONE scraper and save to disk."""
        indexer = _package_indexer()

        trials = indexer.scrape_clinicaltrials_gov()
        if not trials:
            raise ValueError(
                "scrape_clinicaltrials_gov() returned no trials. Refusing to "
                "continue: rebuilding an index from an empty scrape would "
                "replace a good collection with an empty one.")

        indexer.save_trials_to_disk(trials, output_path=DATA_TRIAL_PATH)
        return str(Path(DATA_TRIAL_PATH) / "trials_latest.json")

    @task(task_id="rebuild_index")
    def rebuild_index(trials_file: str) -> dict:
        """Build a staging collection, VERIFY IT, then swap. Keeps a rollback.

        The order is create -> index -> payload index -> verify -> swap ->
        cleanup(keep 2). Verification happens BEFORE the alias moves, so a
        staging collection that failed any check leaves production untouched.
        """
        indexer = _package_indexer()
        cfg = _load_config()
        alias = cfg["COLLECTION_NAME"]

        with open(trials_file, "r") as f:
            trials = json.load(f)

        previous = indexer.resolve_alias_target(alias)

        # The staging name is derived from the alias this task will SWAP ONTO,
        # never from a literal. It used to read "trial_criteria_" + timestamp
        # while `alias` came from cfg["COLLECTION_NAME"], so the two could name
        # different families -- and the cleanup call below enumerates the alias
        # family, which would then have left every collection this task built
        # behind while deleting members of a family it did not build. Deriving
        # it here also keeps the DAG free of a config import for a fact it
        # already holds.
        staging_name = alias + "_" + datetime.now().strftime("%Y%m%d_%H%M%S")

        indexer.create_qdrant_collection(staging_name, delete_if_exists=False)
        indexer.index_trials(trials, collection_name=staging_name)
        indexer.create_payload_indexes(staging_name)

        # Raises IndexVerificationError, which fails the task and leaves the
        # alias exactly where it was.
        indexer.verify_collection(staging_name, expected_count=len(trials))

        indexer.swap_alias_atomic(staging_name, alias)
        indexer.cleanup_old_collections(keep_recent=2, alias_name=alias)

        return {"collection": staging_name,
                "expected": len(trials),
                "rollback_target": previous}

    @task(task_id="verify_index")
    def verify_index(built: dict):
        """Re-verify AFTER the swap, and confirm the alias actually moved.

        This is not the gate -- rebuild_index already gated on the same checks
        before promoting. It answers the different question of whether the
        thing now serving traffic is the thing that was verified.
        """
        indexer = _package_indexer()
        cfg = _load_config()
        alias = cfg["COLLECTION_NAME"]

        live = indexer.resolve_alias_target(alias)
        if live != built["collection"]:
            raise ValueError(
                "alias " + repr(alias) + " points at " + repr(live) +
                ", not at the collection this run built and verified (" +
                repr(built["collection"]) + ").")

        indexer.verify_collection(built["collection"],
                                  expected_count=built["expected"])
        print("Live collection " + repr(live) + " verified after swap. "
              "Rollback target: " + repr(built.get("rollback_target")))

    # TaskFlow dependency chain (XCom passes data automatically)
    trials_file = scrape_and_save()
    built = rebuild_index(trials_file)
    verify_index(built)


# Register DAG
trial_refresh_weekly()
'''


def build_dag_content(code_path=None, keys_path=None, data_trial_path=None):
    """Assemble the whole DAG text: head + rendered path block + tail.

    Args:
        code_path, keys_path, data_trial_path: passed through to
            ``build_path_block``. None means "resolve it from
            ``oncotriage.paths`` on this call".

    Returns:
        The complete DAG source as a string.

    This is the function File 23's module-level ``dag_content = head + block +
    tail`` became. The concatenation is identical; only the moment it happens
    moved, from import to call.
    """
    return (dag_content_head
            + build_path_block(code_path, keys_path, data_trial_path)
            + dag_content_tail)


#------------------------------------------------------------------------------


# Write DAG file
# Item 20b: creating the dags/ directory and writing the file were both module
# level, so loading this file wrote to disk.
def write_dag_file(dags_root, content=None):
    """Write the generated DAG under dags_root, unless a different one is there.

    Args:
        dags_root: The AIRFLOW_HOME. The file lands at ``dags_root/dags/``.
        content:   The DAG text. None calls ``build_dag_content()``, which is
                   what File 23's module-level ``dag_content`` supplied. Passing
                   it explicitly lets a caller write text it built with
                   overridden paths, without a second resolution.

    Returns the destination path. Refuses to overwrite a file whose text
    differs from the generated content, in case it was edited in place.
    """
    if content is None:
        content = build_dag_content()

    dag_dir = Path(dags_root) / 'dags'
    dag_dir.mkdir(parents=True, exist_ok=True)
    dag_file = dag_dir / 'trial_refresh_weekly.py'

    # If it exists
    if dag_file.exists():
        if dag_file.read_text() == content:
            console.out(f"✓ DAG file already exists and matches this generator: {dag_file}")
        else:
            console.out(f"! DAG file already exists and DIFFERS from this generator: {dag_file}")
            console.out("  Not overwriting, in case it was edited in place.")
            console.out("  The scheduler parses that file, not the string in this one, so every")
            console.out("  edit made here -- including the schedule -- is inert until it is replaced.")
            console.out("  Delete it and re-run this file to regenerate.")
    else:
        dag_file.write_text(content)
        console.out(f"✓ New DAG file created: {dag_file}")

    return dag_file


def write_dag_file_to_default(content=None):
    """Write the DAG under the resolved AIRFLOW_HOME.

    The one call File 23's ``__main__`` block made, with the path resolved here
    rather than read out of the exec namespace. Kept separate from
    ``write_dag_file`` so that the writer itself never resolves a directory --
    a caller who names its own destination resolves nothing at all.
    """
    return write_dag_file(resolve_airflow_home(), content=content)


#------------------------------------------------------------------------------


#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 16 17:08:13 2026

@author: ramyalsaffar
"""
